 //BUBBLE SORT
/*
* This code is generated by KRISHNA AGRAWAL
*/


#include "ArrayInput.cpp"
static int k=0;
int ext=6;

class BubbleSort
{
	public:	
    int data[7];
	int *arr;
	void performBubbleSort();	
};

void BubbleSort :: performBubbleSort() 	
{	
	ArrayInput ai;
	ai.inputFrame(5); //5 means -> ArrayInput is called by Bubble Sort
	arr=ai.getdata(5); 
	for(int i=0;i<7;i++) //indicates that, This call from bubble sort
	{
		data[i]= arr[i];
	}
	_Main obj;
	obj.init();
		
	int a=0,i=100,j=150;
	char pass[20]; //int k=1;
	settextstyle(10,0,5);//font_style,horizontal,font_size
	bool if_entered = false;	
		
	int temp,t=0,nand=0;
	char key[20];
	int dataX=100,dataY=125;
		
	for(int step=0;step<7;step++) // Loop1[start] ~ BubbleSort main outer loop
	{
		obj.footer();
		settextstyle(10,0,7);
		setcolor(YELLOW);	outtextxy(120,20,"BUBBLE SORT");
		sprintf(pass,"Pass --> %d",++k);
		setcolor(CYAN);		outtextxy(900,20,pass);
		
		settextstyle(10,0,3);
		setcolor(WHITE);
		dataX=100,dataY=125;
		i=100,j=150;
		for(int ij=0;ij<7-1-step;++ij)
		{
			//4 Boundary lines
			line(50,i,50,j);	line(50,j,1400,j);	line(1400,j,1400,i);	line(1400,i,50,i);
			//	inner lines 
 			line(200,i,200,j);	line(400,i,400,j);	line(600,i,600,j);	line(800,i,800,j);	line(1000,i,1000,j);	line(1200,i,1200,j);
			i= i+100;			j= j+100;
			for(int t=0;t<7;t++)  //Loop4[start] ~ For dispalying data
			{
				sprintf(key,"%d",data[t]);
				outtextxy(dataX,dataY,key);
				dataX = dataX+200;	//dataX,dataY ko for loop k bahar declare karna hai
			} // Loop4[end]
			dataY = dataY+100;
			dataX =100;	
					
			if(data[ij]>data[ij+1])
			{
				temp=data[ij];
				data[ij]=data[ij+1];
				data[ij+1]=temp;
				if_entered = true;
			}
					
			if(if_entered)
			{
				setcolor(RED);	settextstyle(10,0,4);
				switch(ij)
				{
					case 0:	outtextxy(160,160,"Swap"); break;		
					case 1: outtextxy(360,260,"Swap"); break;
					case 2:	outtextxy(560,360,"Swap"); break;
					case 3: outtextxy(760,460,"Swap"); break;
					case 4: outtextxy(960,560,"Swap"); break;
					case 5: outtextxy(1160,660,"Swap"); break;
				}
						
				if_entered = false;
			}
			setcolor(15);	settextstyle(10,0,3);
		} //Loop2[end]
			
//			^^^^^^^^^^^^^^^^^^
		
		line(50,i,50,j);	line(50,j,1400,j);	line(1400,j,1400,i);	line(1400,i,50,i);
//				inner lines 
 		line(200,i,200,j);	line(400,i,400,j);	line(600,i,600,j);	line(800,i,800,j);	line(1000,i,1000,j);	line(1200,i,1200,j);
		i= i+100;			j= j+100; 
//				delay(8000);
		for(int t=0;t<7;t++)  //Loop4[start] ~ For dispalying data
		{
			sprintf(key,"%d",data[t]);
			outtextxy(dataX,dataY,key);
			dataX = dataX+200;	
		}
		setfillstyle(1,BLUE);		
				
		int tabX,tabY;
		tabX=100,tabY=110; 
		// BLUE Code
		for(int color=ext;color>0;color--)
		{
			floodfill(tabX,tabY,15); 
			tabX = tabX + 200;
			floodfill(tabX,tabY,15);
			tabY = tabY + 100; 
		} 
				
		// GREEN Code
		int xAxis=1300,yAxis=110;
		setfillstyle(1,GREEN);
		int c7;
		switch(step)//only last wala green k liye
		{
			case 0: 	floodfill(1300,710,15);break;
			case 1:		c7 = 110; for(int y=1;y<=ext+1;y++)
								{
									floodfill(1300,c7,15); 
									c7 += 100;
								}
								floodfill(1100,610,15); break;
			case 2:		c7 = 110; for(int y=1;y<=ext+1;y++)		
								{
									floodfill(1300,c7,15);
									floodfill(1100,c7,15);
									c7 += 100;
								}
								floodfill(900,510,15); break;
			case 3:		c7 = 110; for(int y=1;y<=ext+1;y++)		
								{
									floodfill(1300,c7,15);
									floodfill(1100,c7,15);
									floodfill(900,c7,15);
									c7 += 100;
								}
								floodfill(700,410,15); break;
			case 4:		c7 = 110; for(int y=1;y<=ext+1;y++)		
								{
									floodfill(1300,c7,15);
									floodfill(1100,c7,15);
									floodfill(900,c7,15);
									floodfill(700,c7,15);
									c7 += 100;
								}floodfill(500,310,15); break;
			case 5:     c7 = 110; for(int y=1;y<=ext+1;y++)		
								{
									floodfill(1300,c7,15);
									floodfill(1100,c7,15);
									floodfill(900,c7,15);
									floodfill(700,c7,15);
									floodfill(500,c7,15);
									c7 += 100;
								}floodfill(300,210,15); break;
			case 6:    int x_vary =100 ;for(int u=1;u<=7;u++)
								{
									floodfill(x_vary,110,15);	
									x_vary += 200;
								}			
		}
		ext--;		getch();
		cleardevice();
		
	}//Loop1[end] 
}//End of  performBubbleSort function()

